modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mfletcher2/MineRGB/issues"
license = "GPL-3.0"

[[mods]]
modId = "minergb"
version = "${version}"
displayName = "MineRGB"
authors = "mfletcher"
description = '''
OpenRGB integration for Minecraft
'''
logoFile = "assets/minergb/icon.png"
displayURL = "https://github.com/mfletcher2/MineRGB"

[[dependencies.minergb]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minergb]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minergb]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.minergb]]
modId = "cloth_config"
mandatory = true
versionRange = "[*,)"