modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/mfletcher2/MineRGB/issues"
license = "GPL-3.0"

[[mods]]
modId = "minergb"
version = "${version}"
displayName = "MineRGB"
authors = "mfletcher"
description = '''
OpenRGB integration for Minecraft
'''
logoFile = "assets/minergb/icon.png"
displayURL = "https://github.com/mfletcher2/MineRGB"

[[dependencies.minergb]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minergb]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minergb]]
modId = "architectury"
type = "required"
versionRange = "[12.0.26,)"
ordering = "AFTER"
side = "BOTH"
